# Pandas series

###  A series is a one-dimension array capable of holding any data type. This axis labels are collectively called the index.

In [31]:
import numpy as np
import pandas as pd

In [5]:
labels =['a','b', 'c', 'd']
my_list =[10, 20, 30, 40]
arr = np.array([10, 20, 30, 40])
d = {1:10, 2:20, 3:30, 4:40}

In [6]:
pd.Series(my_list)

0    10
1    20
2    30
3    40
dtype: int64

In [7]:
pd.Series(my_list, index = labels)

a    10
b    20
c    30
d    40
dtype: int64

In [8]:
pd.Series(arr, index = labels)

a    10
b    20
c    30
d    40
dtype: int32

# data frame

In [9]:
data ={
    'Name' : ['john' , 'Anna' , 'peter'],
    'Age' :[28, 30, 42],
    "City": ['Bhopal', "Indore", 'Bagluru'],
    "Salary": [10000, 25000, 50000]
}

pd.DataFrame(data)

    Name  Age     City  Salary
0   john   28   Bhopal   10000
1   Anna   30   Indore   25000
2  peter   42  Bagluru   50000

In [10]:
data_list =[
    ['John', 28, "New York",6500],
    ['Anna', 34, 'Paris',70000],
    ['peter',45, 'Berlin', 64000],
    ['Linda', 42, 'London', 8500]
]

df2 = pd.DataFrame(data_list)

columns = ["Name", "Age", "city","Salary"]

df2 =  pd.DataFrame(data_list , columns = columns)
df2

    Name  Age      city  Salary
0   John   28  New York    6500
1   Anna   34     Paris   70000
2  peter   45    Berlin   64000
3  Linda   42    London    8500

## salecting and indexing of column

In [11]:
df2["city"]

0    New York
1       Paris
2      Berlin
3      London
Name: city, dtype: object

In [12]:
df2[["city", "Salary"]]

       city  Salary
0  New York    6500
1     Paris   70000
2    Berlin   64000
3    London    8500

# creating a new column

In [13]:
df2["Designation"] = ["Doctor","Engg.","Brber","Banker"]

In [14]:
df2

    Name  Age      city  Salary Designation
0   John   28  New York    6500      Doctor
1   Anna   34     Paris   70000       Engg.
2  peter   45    Berlin   64000       Brber
3  Linda   42    London    8500      Banker

## delete only one dataframe not for complete dataframe
here weare using axis = 0 for harizontal and axis = 1 for vertical

In [15]:
df2.drop('Designation', axis = 1)

    Name  Age      city  Salary
0   John   28  New York    6500
1   Anna   34     Paris   70000
2  peter   45    Berlin   64000
3  Linda   42    London    8500

In [16]:
df2

    Name  Age      city  Salary Designation
0   John   28  New York    6500      Doctor
1   Anna   34     Paris   70000       Engg.
2  peter   45    Berlin   64000       Brber
3  Linda   42    London    8500      Banker

# If  you want to delete any column from whole Dataframe then use - Inplace = true

In [17]:
df2.drop('Designation', axis = 1, inplace = True)

In [18]:
df2

    Name  Age      city  Salary
0   John   28  New York    6500
1   Anna   34     Paris   70000
2  peter   45    Berlin   64000
3  Linda   42    London    8500

### salecting rows

In [19]:
df2.loc[[0,1]]

   Name  Age      city  Salary
0  John   28  New York    6500
1  Anna   34     Paris   70000

In [20]:
df2.loc[1]

Name       Anna
Age          34
city      Paris
Salary    70000
Name: 1, dtype: object

## salecting a subset of rows and column

In [21]:
df2.loc[[0,1]][["city","Salary"]]

       city  Salary
0  New York    6500
1     Paris   70000

In [22]:
df2.loc[[2,3]][["Name", "Age"]]

    Name  Age
2  peter   45
3  Linda   42

## conditional salection

In [23]:
df2

    Name  Age      city  Salary
0   John   28  New York    6500
1   Anna   34     Paris   70000
2  peter   45    Berlin   64000
3  Linda   42    London    8500

In [24]:
# i want to see those people whose age is greater than 30

In [25]:
df2[df2["Age"]> 30]

    Name  Age    city  Salary
1   Anna   34   Paris   70000
2  peter   45  Berlin   64000
3  Linda   42  London    8500

In [26]:
df2[(df2["Age"] > 30) & (df2["city"] == "Paris") ]

   Name  Age   city  Salary
1  Anna   34  Paris   70000

# Finding Missing data

In [30]:
data ={
    'A': [1, 2 ,3 ,np.nan,4],
    'B': [np.nan ,2,3,4, 5],
    'C': [1,2,3, np.nan, np.nan],
    'D': [1, np.nan ,np.nan,np.nan,5]
}
df3 = pd.DataFrame(data)

#### find total no. of nan value present in a column

In [34]:
df3.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [32]:
df3

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  3.0  3.0  3.0  NaN
3  NaN  4.0  NaN  NaN
4  4.0  5.0  NaN  5.0

### find krna hai ki kya sabhi column me nan value present hai ya nhi

In [36]:
df3.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [38]:
df3.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2  False  False  False   True
3   True  False   True   True
4  False  False   True  False

# Rwmoving missing data

In [37]:
df3

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  3.0  3.0  3.0  NaN
3  NaN  4.0  NaN  NaN
4  4.0  5.0  NaN  5.0

In [39]:
df3.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [40]:
df3

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  3.0  3.0  3.0  NaN
3  NaN  4.0  NaN  NaN
4  4.0  5.0  NaN  5.0

# thresh ka use least nan value ke liye hai
yadi thresh = 3 likh raha jis se yah pata chale ga ki kis me 3 nan value hai and drop ka use hatane ke liye hai , jis se jis me 3 nan value hogi o hat  jaye ga

In [44]:
df3.dropna(thresh = 1)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  3.0  3.0  3.0  NaN
3  NaN  4.0  NaN  NaN
4  4.0  5.0  NaN  5.0

## Filling the missing data

In [45]:
df3

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  3.0  3.0  3.0  NaN
3  NaN  4.0  NaN  NaN
4  4.0  5.0  NaN  5.0

In [46]:
df3.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  3.0  3.0  3.0  0.0
3  0.0  4.0  0.0  0.0
4  4.0  5.0  0.0  5.0

In [47]:
values = {'A': 0, 'B': 100, 'C': 300, 'D': 400}
df3.fillna(value = values)

     A      B      C      D
0  1.0  100.0    1.0    1.0
1  2.0    2.0    2.0  400.0
2  3.0    3.0    3.0  400.0
3  0.0    4.0  300.0  400.0
4  4.0    5.0  300.0    5.0

In [48]:
df3.fillna(df3.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  2.5  4.0  2.0  3.0
4  4.0  5.0  2.0  5.0

# Merging Joining Concatination

In [52]:
# DataFrace1 : 

employees = pd.DataFrame({
    'employees_id': [1,2,3,4,5],
    'Name': ['john','Anna','Peter','limda','Boss'],
    'department':['HR','It','Finance', 'It','It']
})


#DataFrame 2:
Salaries = pd.DataFrame({
    'employees_id' : [ 1 , 2 , 3 , 6 , 7 ],
    'Salary': [60000, 43000,45000,70000,65000]
})

In [53]:
employees

   employees_id   Name department
0             1   john         HR
1             2   Anna         It
2             3  Peter    Finance
3             4  limda         It
4             5   Boss         It

In [54]:
Salaries

   employees_id  Salary
0             1   60000
1             2   43000
2             3   45000
3             6   70000
4             7   65000

In [55]:
pd.merge(employees, Salaries , on = "employees_id", how = "inner")

   employees_id   Name department  Salary
0             1   john         HR   60000
1             2   Anna         It   43000
2             3  Peter    Finance   45000

In [58]:
pd.merge(employees, Salaries , on = "employees_id", how = "outer")

   employees_id   Name department   Salary
0             1   john         HR  60000.0
1             2   Anna         It  43000.0
2             3  Peter    Finance  45000.0
3             4  limda         It      NaN
4             5   Boss         It      NaN
5             6    NaN        NaN  70000.0
6             7    NaN        NaN  65000.0

In [60]:
pd.merge(employees, Salaries , on = "employees_id", how = "left")

   employees_id   Name department   Salary
0             1   john         HR  60000.0
1             2   Anna         It  43000.0
2             3  Peter    Finance  45000.0
3             4  limda         It      NaN
4             5   Boss         It      NaN

In [61]:
pd.merge(employees, Salaries , on = "employees_id", how = "right")

   employees_id   Name department  Salary
0             1   john         HR   60000
1             2   Anna         It   43000
2             3  Peter    Finance   45000
3             6    NaN        NaN   70000
4             7    NaN        NaN   65000

## Concationation of two dataframe

In [62]:
# DataFrace1 : 

df4 = pd.DataFrame({
    'employees_id': [1,2,3,4,5],
    'Name': ['john','Anna','Peter','limda','Boss'],
    'department':['HR','It','Finance', 'It','It']
})


#DataFrame 
df5 = pd.DataFrame({
    'employees_id' : [ 1 , 2 , 3 , 6 , 7 ],
    'Salary': [60000, 43000,45000,70000,65000]
})

In [64]:
pd.concat([df4,df5])

   employees_id   Name department   Salary
0             1   john         HR      NaN
1             2   Anna         It      NaN
2             3  Peter    Finance      NaN
3             4  limda         It      NaN
4             5   Boss         It      NaN
0             1    NaN        NaN  60000.0
1             2    NaN        NaN  43000.0
2             3    NaN        NaN  45000.0
3             6    NaN        NaN  70000.0
4             7    NaN        NaN  65000.0

In [65]:
pd.concat([df4,df5], axis = 1)

   employees_id   Name department  employees_id  Salary
0             1   john         HR             1   60000
1             2   Anna         It             2   43000
2             3  Peter    Finance             3   45000
3             4  limda         It             6   70000
4             5   Boss         It             7   65000

** joining 2 dataframe

In [71]:
df6 = pd.DataFrame({
     'Name': ['john','Anna','Peter','limda','Boss']
}, index = [1,2,3,4,5])

df7 = pd.DataFrame({
    'Score' : [80, 78,90, 50, 85],
}, index = [2,3,4,5,6])

In [72]:
df6

    Name
1   john
2   Anna
3  Peter
4  limda
5   Boss

In [73]:
df7

   Score
2     80
3     78
4     90
5     50
6     85

In [76]:
df6.join(df7)

    Name  Score
1   john    NaN
2   Anna   80.0
3  Peter   78.0
4  limda   90.0
5   Boss   50.0

In [78]:
df6.join(df7,how = 'inner')

    Name  Score
2   Anna     80
3  Peter     78
4  limda     90
5   Boss     50

# Group by Aggrigation

In [5]:
data = {
    'Categry' : ['A','B','A','B','A','B'],
    'Store' : ['s1','s2','s2', 's1','s1','s2'],
    'Sale' : [100 , 200 , 300 , 400 , 500 , 600],
    'Quanty': [10 , 20 , 30 , 40 , 50 , 60],
    'Date' : pd.date_range('2026 - 06 - 13', periods = 6)
}

df8 = pd.DataFrame(data)

In [104]:
df8

  Categry Store  Sale  Quanty       Date
0       A    s1   100      10 2026-06-13
1       B    s2   200      20 2026-06-14
2       A    s2   300      30 2026-06-15
3       B    s1   400      40 2026-06-16
4       A    s1   500      50 2026-06-17
5       B    s2   600      60 2026-06-18

In [10]:
df8[["Sale","Quanty"]]

   Sale  Quanty
0   100      10
1   200      20
2   300      30
3   400      40
4   500      50
5   600      60

In [3]:
# group by categry and calculate the sum of sales
cat = df8.groupby('Categry')
cat

for i , v in cat:
    print(i)
    print(v)

A
  Categry Store  Sale  Quanty       Date
0       A    s1   100      10 2026-06-13
2       A    s2   300      30 2026-06-15
4       A    s1   500      50 2026-06-17
B
  Categry Store  Sale  Quanty       Date
1       B    s2   200      20 2026-06-14
3       B    s1   400      40 2026-06-16
5       B    s2   600      60 2026-06-18

In [16]:
cat = df8.groupby('Categry')['Sale'].sum()
cat

Categry
A     900
B    1200
Name: Sale, dtype: int64

In [6]:
# Group by store and calculate the sum of sales
cat = df8.groupby('Store')['Sale'].sum()
cat

Store
s1    1000
s2    1100
Name: Sale, dtype: int64

In [7]:
cat = df8.groupby(['Categry','Store'])['Sale'].sum()
cat

Categry  Store
A        s1       600
         s2       300
B        s1       400
         s2       800
Name: Sale, dtype: int64

# Aggregation

In [8]:
df8['Sale'].sum()

2100

In [9]:
df8['Sale'].agg(['sum','mean','min','max','count','std','median'])

sum       2100.000000
mean       350.000000
min        100.000000
max        600.000000
count        6.000000
std        187.082869
median     350.000000
Name: Sale, dtype: float64

# Pivot Tables

In [19]:
data ={
    "Date": pd.date_range('2026-06-14',periods = 20),
    "Product": ['A','B','C','D'] * 5,
    "Region": ['East','West','North','South','East','West','North','South','East',
               'West','North','South','East','West','North','South','East','West','North','South'],
    "Sales": np.random.randint( 100, 1000,20),
    "Units": np.random.randint(10 ,100 , 20),
    "Rep": ['John','Mary','Bob', 'Alice','John','Mary','Bob', 'Alice','John',
            'Mary','Bob', 'Alice','John','Mary','Bob', 'Alice','John','Mary','Bob', 'Alice'],
    
}
df9 = pd.DataFrame(data)

df9['Month'] = df['Date'].dt.month_name()
df9['Quarter'] = 'Q'  + df['Date'].dt.quarter.astype(str)
df9

         Date Product Region  Sales  Units    Rep Month Quarter
0  2026-06-14       A   East    951     99   John  June      Q2
1  2026-06-15       B   West    723     16   Mary  June      Q2
2  2026-06-16       C  North    158     57    Bob  June      Q2
3  2026-06-17       D  South    798     39  Alice  June      Q2
4  2026-06-18       A   East    479     71   John  June      Q2
5  2026-06-19       B   West    512     65   Mary  June      Q2
6  2026-06-20       C  North    358     91    Bob  June      Q2
7  2026-06-21       D  South    866     72  Alice  June      Q2
8  2026-06-22       A   East    777     13   John  June      Q2
9  2026-06-23       B   West    602     36   Mary  June      Q2
10 2026-06-24       C  North    138     55    Bob  June      Q2
11 2026-06-25       D  South    386     10  Alice  June      Q2
12 2026-06-26       A   East    167     65   John  June      Q2
13 2026-06-27       B   West    269     37   Mary  June      Q2
14 2026-06-28       C  North    970     98    Bob  June      Q2
15 2026-06-29       D  South    204     53  Alice  June      Q2
16 2026-06-30       A   East    538     87   John  June      Q2
17 2026-07-01       B   West    166     50   Mary  July      Q3
18 2026-07-02       C  North    427     91    Bob  July      Q3
19 2026-07-03       D  South    722     51  Alice  July      Q3

In [28]:
pd.pivot_table(df9, values = "Sales",index = "Region", columns ="Product",aggfunc = "median")

Product      A      B      C      D
Region
East     538.0    NaN    NaN    NaN
North      NaN    NaN  358.0    NaN
South      NaN    NaN    NaN  722.0
West       NaN  512.0    NaN    NaN

In [29]:
pvt2 = pd.pivot_table(df9, values =["Sales", "Units"],index = "Region", columns ="Product")
pvt2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     582.4    NaN    NaN    NaN  67.0   NaN   NaN   NaN
North      NaN    NaN  410.2    NaN   NaN   NaN  78.4   NaN
South      NaN    NaN    NaN  595.2   NaN   NaN   NaN  45.0
West       NaN  454.4    NaN    NaN   NaN  40.8   NaN   NaN

In [30]:
pd.crosstab(df9['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# Operation

In [32]:
df10 = pd.DataFrame({
    'A': [1,2,3,4,5],
    'B': [10,20,30,40,50],
    'C': [100,200,300,400,500]
})

In [33]:
df10

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [36]:
df10.shape

(5, 3)

In [37]:
df10.columns

Index(['A', 'B', 'C'], dtype='object')

In [51]:
df10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
 3   D       5 non-null      int64
dtypes: int64(4)
memory usage: 292.0 bytes

In [39]:
df10.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [40]:
df10["A"] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

## DataFrame applying functions

In [41]:
df10

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [42]:
def square(x):
    return x**2

In [43]:
df10["B"].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [45]:
df10["B"] =df10["B"].apply(square)
df10

   A        B    C
0  1    10000  100
1  2   160000  200
2  3   810000  300
3  4  2560000  400
4  5  6250000  500

In [50]:
df10["D"] =df10["C"].apply(square)
df10

   A        B    C       D
0  1    10000  100   10000
1  2   160000  200   40000
2  3   810000  300   90000
3  4  2560000  400  160000
4  5  6250000  500  250000